import { z } from 'zod';
export declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    JWT_ACCESS_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_ACCESS_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    PAYSTACK_SECRET_KEY: z.ZodDefault<z.ZodString>;
    PAYSTACK_PUBLIC_KEY: z.ZodDefault<z.ZodString>;
    PAYSTACK_TEST_MODE: z.ZodDefault<z.ZodBoolean>;
    STORAGE_ENDPOINT: z.ZodDefault<z.ZodString>;
    STORAGE_ACCESS_KEY: z.ZodDefault<z.ZodString>;
    STORAGE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    STORAGE_BUCKET: z.ZodDefault<z.ZodString>;
    STORAGE_PUBLIC_URL: z.ZodDefault<z.ZodString>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["console", "smtp", "resend"]>>;
    EMAIL_FROM: z.ZodDefault<z.ZodString>;
    SMTP_HOST: z.ZodDefault<z.ZodString>;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_USER: z.ZodDefault<z.ZodString>;
    SMTP_PASS: z.ZodDefault<z.ZodString>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    RATE_LIMIT_TTL: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    STORE_CURRENCY: z.ZodDefault<z.ZodString>;
    STORE_NAME: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_ACCESS_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    PAYSTACK_SECRET_KEY: string;
    PAYSTACK_PUBLIC_KEY: string;
    PAYSTACK_TEST_MODE: boolean;
    STORAGE_ENDPOINT: string;
    STORAGE_ACCESS_KEY: string;
    STORAGE_SECRET_KEY: string;
    STORAGE_BUCKET: string;
    STORAGE_PUBLIC_URL: string;
    EMAIL_PROVIDER: "console" | "smtp" | "resend";
    EMAIL_FROM: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_USER: string;
    SMTP_PASS: string;
    CORS_ORIGINS: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_MAX: number;
    STORE_CURRENCY: string;
    STORE_NAME: string;
}, {
    DATABASE_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    REDIS_URL?: string | undefined;
    JWT_ACCESS_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    PAYSTACK_SECRET_KEY?: string | undefined;
    PAYSTACK_PUBLIC_KEY?: string | undefined;
    PAYSTACK_TEST_MODE?: boolean | undefined;
    STORAGE_ENDPOINT?: string | undefined;
    STORAGE_ACCESS_KEY?: string | undefined;
    STORAGE_SECRET_KEY?: string | undefined;
    STORAGE_BUCKET?: string | undefined;
    STORAGE_PUBLIC_URL?: string | undefined;
    EMAIL_PROVIDER?: "console" | "smtp" | "resend" | undefined;
    EMAIL_FROM?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    CORS_ORIGINS?: string | undefined;
    RATE_LIMIT_TTL?: number | undefined;
    RATE_LIMIT_MAX?: number | undefined;
    STORE_CURRENCY?: string | undefined;
    STORE_NAME?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema>;
export declare function loadEnv(env?: NodeJS.ProcessEnv): EnvConfig;
export declare const ROLES: {
    readonly SUPER_ADMIN: "SUPER_ADMIN";
    readonly ADMIN: "ADMIN";
    readonly STORE_MANAGER: "STORE_MANAGER";
    readonly INVENTORY_MANAGER: "INVENTORY_MANAGER";
    readonly ORDER_MANAGER: "ORDER_MANAGER";
    readonly CONTENT_EDITOR: "CONTENT_EDITOR";
    readonly MARKETING_MANAGER: "MARKETING_MANAGER";
    readonly WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER";
    readonly CASHIER: "CASHIER";
    readonly CUSTOMER: "CUSTOMER";
};
export type RoleName = (typeof ROLES)[keyof typeof ROLES];
export declare const DEFAULT_CURRENCY = "NGN";
export declare const DEFAULT_LOCALE = "en";
export declare const ORDER_STATUSES: readonly ["PENDING", "PAID", "PROCESSING", "PACKED", "SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"];
export type OrderStatus = (typeof ORDER_STATUSES)[number];
export declare const PAYMENT_STATUSES: readonly ["PENDING", "INITIALIZED", "SUCCESSFUL", "FAILED", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"];
export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];
export declare const INVENTORY_TRANSACTION_TYPES: readonly ["PURCHASE", "SALE", "RETURN", "ADJUSTMENT", "TRANSFER", "DAMAGED", "MANUAL_CORRECTION"];
export type InventoryTransactionType = (typeof INVENTORY_TRANSACTION_TYPES)[number];
export declare const PRODUCT_STATUSES: readonly ["DRAFT", "ACTIVE", "OUT_OF_STOCK", "ARCHIVED"];
export type ProductStatus = (typeof PRODUCT_STATUSES)[number];
export declare const CONTENT_STATUSES: readonly ["DRAFT", "PUBLISHED", "SCHEDULED", "ARCHIVED"];
export type ContentStatus = (typeof CONTENT_STATUSES)[number];
export declare const REVIEW_STATUSES: readonly ["PENDING", "APPROVED", "REJECTED"];
export type ReviewStatus = (typeof REVIEW_STATUSES)[number];
